[package]
name = "Pocket_Pet"
version = "0.1.0"
edition = "2024"

[dependencies]
mrdirector = "0.2.0"
turbo = { version = "4.0.0-alpha.8", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }

