name = "Pocket_Pet"
version = "0.1.0"
description = "A virtual pet sim that wants your money"
authors = ["Caleb Jeon and Anna Shimizu"]

[canvas]
width = 240
height = 160

[turbo-os]
api-url = "https://os.turbo.computer"